version: "3"

services:
  client:
    container_name: wyvate-website
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./:/src
    working_dir: /usr/src/app

